### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by Drewster727** [alexvaut/cStatsExporter#8]
I'm running into an odd issue where the memory on the exporter container slowly creeps up over time:
![image](https://user-images.githubusercontent.com/4528753/79411545-b2202980-7f68-11ea-8e5d-9ddfad928f73.png)
![image](https://user-images.githubusercontent.com/4528753/79411902-b7ca3f00-7f69-11ea-8eb2-2731f902dce4.png)
(the drops are from host/docker restarts)

Using latest code from master branch as of April 15, 2020.
Docker 19.03.5
Windows Server 1903

I did adjust the Dockerfile to pull in nanoserver instead of windowservercore so it would be a lighter image:
```
FROM golang:nanoserver as builder
#FROM golang:windowsservercore as builder

#Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build the application
RUN go build -o main.exe .

FROM mcr.microsoft.com/windows/nanoserver:1903-amd64

USER ContainerAdministrator

WORKDIR /app

# Expose port 9030 to the outside world
EXPOSE 9030

ARG DOCKER_API_VERSION=1.24

ENV DOCKER_API_VERSION=$DOCKER_API_VERSION

COPY config.yml /app/config.yml
COPY --from=builder /build/main.exe /app/

ENTRYPOINT ["C:/app/main.exe"]
```

However, I don't think my Dockerfile changes are causing this memory increase.

Any tips on pinpointing this?

@alexvaut

**Comment by alexvaut** [comment]
Hi,

Thanks for looking into this: 

1/ docker image: it was already under nanoserver but I was building it externaly, thanks for adding the build inside docker, I might use it.

2/ memory leak: it certainly looks like a leak and a good one !I will fix it as soon as I can.

**Comment by Drewster727** [comment]
@alexvaut ah you're right on the image! I think I meant I switched mine over to windowsservercore temporarily for some reason. Trying to remember why... oh well.

I can see if I can get a heap dump and find out what's consuming all the memory, but I am not a go expert.

Thanks!

**Comment by alexvaut** [comment]
Fixed the docker connection was not closed.
